apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-localhost
  labels:
    name: myingress
spec:
  rules:
  - host: ariel.samoha.king
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service: 
            name: myapp
            port: 
              number: 80
